In [46]:
from dotenv import load_dotenv
import os

In [6]:
#sample input

In [8]:
patient_symptons = ['Fever' , 'Headache' , 'Soreness']

In [11]:
patient_condition = {
    "Age": 67,
    "Mobility Issues": "Requires cane for walking; limited stamina when standing for extended periods",
    "Known Allergies": ["Penicillin", "Latex"],
    "Chronic Conditions": ["Type 2 Diabetes", "Mild Hypertension"],
    "Recent Surgeries": "Hip replacement (8 months ago)",
    "Immunization Status": "Up-to-date, including flu and COVID-19 boosters",
    "Other Notes": "Reports occasional dizziness and sensitivity to cold weather"
}
patient_condition

{'Age': 67,
 'Mobility Issues': 'Requires cane for walking; limited stamina when standing for extended periods',
 'Known Allergies': ['Penicillin', 'Latex'],
 'Chronic Conditions': ['Type 2 Diabetes', 'Mild Hypertension'],
 'Recent Surgeries': 'Hip replacement (8 months ago)',
 'Immunization Status': 'Up-to-date, including flu and COVID-19 boosters',
 'Other Notes': 'Reports occasional dizziness and sensitivity to cold weather'}

In [34]:
geographic_location = {
    "Country": "United States",
    "State": "Kentucky",
    "City": "Highland Heights",
    "Zip Code": "41076",
    "Coordinates": {
        "Latitude": 39.1311,
        "Longitude": -84.5083
    },
    "Preferred Mode of Care": "In person"
}

In [14]:
#The first thing we would calculate is something like nearest health care centers or hospitals based on location

In [18]:
from geopy.distance import geodesic
import pandas as pd

In [21]:
# Sample list of hospitals with coordinates (for demo purposes)
hospital_data = [
    {"Name": "University of Cincinnati Medical Center", "Latitude": 39.1412, "Longitude": -84.5059},
    {"Name": "Cincinnati VA Medical Center", "Latitude": 39.1398, "Longitude": -84.5039},
    {"Name": "Christ Hospital", "Latitude": 39.1231, "Longitude": -84.5070},
    {"Name": "Cleveland Clinic", "Latitude": 41.5033, "Longitude": -81.6200},
    {"Name": "Mount Carmel East", "Latitude": 39.9828, "Longitude": -82.8291}
]
#make a dataframe of this, in reality this will I think be one dataframe per state, consisteing of all health care and hospital services in that area
df_hospitals = pd.DataFrame(hospital_data)

                                      Name  Latitude  Longitude
0  University of Cincinnati Medical Center   39.1412   -84.5059
1             Cincinnati VA Medical Center   39.1398   -84.5039
2                          Christ Hospital   39.1231   -84.5070
3                         Cleveland Clinic   41.5033   -81.6200
4                        Mount Carmel East   39.9828   -82.8291

In [35]:
print("df_hospitals can also include things like what services are offered, which department and nuimber of employees; this is bascially a very big table")

df_hospitals can also include things like what services are offered, which department and nuimber of employees; this is bascially a very big table

In [23]:
#One example of  us calculating distance from patient to each hospital
latitude = geographic_location["Coordinates"]["Latitude"]
longitude = geographic_location["Coordinates"]["Longitude"]
patient_coords = (latitude, longitude)
patient_coords

(39.1311, -84.5083)

In [25]:
#I can do many things in order to calculate the actual distance based on latitide and longitide, maybe subtract both and keep the one with the lowest difference
# KNN? Overkill
# I think there might be libraries that do that properly
#geodesic offers a miles bersion that extract miles from distance, which is nice. I a,m going to do that

In [27]:
distances = []
# Calculate distance for each hospital
for index, row in df_hospitals.iterrows():
    hospital_coords = (row["Latitude"], row["Longitude"])
    distance = geodesic(patient_coords, hospital_coords).miles
    distances.append(distance)
distances

[0.7085628278211792,
 0.6450317424197475,
 0.5562695371259393,
 223.71261059390406,
 107.20597664086802]

In [28]:
#The lowest distance is our hospital

In [57]:
df_hospitals["Distance_miles"] = distances
df_hospitals

,Name,Latitude,Longitude,Distance_miles
0,University of Cincinnati Medical Center,39.1412,-84.5059,0.708563
1,Cincinnati VA Medical Center,39.1398,-84.5039,0.645032
2,Christ Hospital,39.1231,-84.5070,0.556270
3,Cleveland Clinic,41.5033,-81.6200,223.712611
4,Mount Carmel East,39.9828,-82.8291,107.205977

In [37]:
closest_index = df_hospitals["Distance_miles"].idxmin() #find the id of the minimum
closest_hospital = df_hospitals.loc[closest_index, "Name"] #look up the name of the minimum
print("The closest hospital is", closest_hospital)
#Actually, gemini is smart enough for now to choose a hoispital for us based on the values as well.

The closest hospital is Christ Hospital

In [38]:
#I think I can use Gemini to build a basic pipeline for me now

In [39]:
#For now I will just use the base model but I can tinker with it later and use some RAG for the customized treatment plan.
#As long as I dont get the treatement plan, I wont be able to fine tune the model.
#Plus base gemini is jsut as fine, can do most of the stuff

In [45]:
#my second version will make a AI agent class but this notebook will only work on the base base base version
from google import genai

In [48]:
load_dotenv()
client = genai.Client(api_key= os.getenv('Gemini_Api_Key'))
client

In [49]:
#Sample response
response = client.models.generate_content(
    model="gemini-2.0-flash", contents="Explain how AI works in a few words"
)
print(response.text)

AI learns from data to make predictions or decisions.

In [50]:
#Now the first step is prompt engineerning. That solves most of our problems

In [58]:
prompt = f'''
You are a healthcare AI assistant tasked with generating a customized treatment plan for a patient. Given the following inputs:
1. List of patient symptoms which is {patient_symptons}
2. Patient's physical condition which is {patient_condition}
3. Geographic location which is {geographic_location}
Also the list of hospitals are listed below: {df_hospitals}
Generate a detailed treatment plan that includes the following:

1.Suggested medical actions: Specify appropriate steps such as scheduling a primary care visit, recommending lab tests or imaging, referrals to specialists, or urgent care if needed.
2.Location-specific considerations: Based on the patient’s location, recommend nearby clinics, hospitals, or telehealth options within a reasonable distance.
3.Justifications: For every suggested action, include a clear, medically-sound justification based on the patient’s symptoms and conditions.

Format your output in three clearly labeled sections:
1. Medical Actions
2. Location-Specific Options
3. Justifications

Be concise, medically accurate, and context-aware. Avoid unnecessary medical jargon.

'''
prompt

"\nYou are a healthcare AI assistant tasked with generating a customized treatment plan for a patient. Given the following inputs:\n1. List of patient symptoms which is ['Fever', 'Headache', 'Soreness']\n2. Patient's physical condition which is {'Age': 67, 'Mobility Issues': 'Requires cane for walking; limited stamina when standing for extended periods', 'Known Allergies': ['Penicillin', 'Latex'], 'Chronic Conditions': ['Type 2 Diabetes', 'Mild Hypertension'], 'Recent Surgeries': 'Hip replacement (8 months ago)', 'Immunization Status': 'Up-to-date, including flu and COVID-19 boosters', 'Other Notes': 'Reports occasional dizziness and sensitivity to cold weather'}\n3. Geographic location which is {'Country': 'United States', 'State': 'Kentucky', 'City': 'Highland Heights', 'Zip Code': '41076', 'Coordinates': {'Latitude': 39.1311, 'Longitude': -84.5083}, 'Preferred Mode of Care': 'In person'}\nAlso the list of hospitals are listed below:                                       Name  Latitude  Longitude  \\\n0  University of Cincinnati Medical Center   39.1412   -84.5059   \n1             Cincinnati VA Medical Center   39.1398   -84.5039   \n2                          Christ Hospital   39.1231   -84.5070   \n3                         Cleveland Clinic   41.5033   -81.6200   \n4                        Mount Carmel East   39.9828   -82.8291   \n\n   Distance_miles  \n0        0.708563  \n1        0.645032  \n2        0.556270  \n3      223.712611  \n4      107.205977  \nGenerate a detailed treatment plan that includes the following:\n\n1.Suggested medical actions: Specify appropriate steps such as scheduling a primary care visit, recommending lab tests or imaging, referrals to specialists, or urgent care if needed.\n2.Location-specific considerations: Based on the patient’s location, recommend nearby clinics, hospitals, or telehealth options within a reasonable distance.\n3.Justifications: For every suggested action, include a clear, medically-sound justification based on the patient’s symptoms and conditions.\n\nFormat your output in three clearly labeled sections:\n1. Medical Actions\n2. Location-Specific Options\n3. Justifications\n\nBe concise, medically accurate, and context-aware. Avoid unnecessary medical jargon.\n\n"

In [59]:
#Sample response
response = client.models.generate_content(
    model="gemini-2.0-flash", contents= prompt
)
response.text

"Here's a proposed treatment plan based on the provided patient information.\n\n**1. Medical Actions**\n\n*   **Schedule a Primary Care Visit:** Within 24-48 hours.\n*   **Recommend Lab Tests:** CBC (Complete Blood Count), CRP (C-Reactive Protein), and basic metabolic panel.\n*   **Advise rest and supportive care:** Get adequate rest, stay hydrated, and consider over-the-counter fever reducers/pain relievers like acetaminophen (Tylenol) or ibuprofen (Advil), being mindful of potential interactions with existing medications.\n\n**2. Location-Specific Options**\n\n*   **Nearest Hospitals (for potential urgent care if symptoms worsen significantly):**\n    *   Christ Hospital (approximately 0.56 miles from patient's coordinates).\n    *   Cincinnati VA Medical Center (approximately 0.65 miles from patient's coordinates).\n    *   University of Cincinnati Medical Center (approximately 0.71 miles from patient's coordinates).\n*   **Consider in-person visit:** Given the patient's reported occasional dizziness, preferred mode of care, and age, an in-person assessment is preferred over a telehealth visit initially.\n\n**3. Justifications**\n\n*   **Schedule a Primary Care Visit:** The combination of fever, headache, and soreness is indicative of a potential infection (viral or bacterial) or inflammatory process. A primary care physician can assess the patient's overall condition, rule out serious causes, and prescribe appropriate treatment.\n*   **Recommend Lab Tests (CBC, CRP, Basic Metabolic Panel):**\n    *   *CBC:* Helps to identify signs of infection (elevated white blood cell count) or other blood disorders.\n    *   *CRP:* An elevated CRP level indicates inflammation in the body, which can help differentiate between viral and bacterial infections and assess the severity of the inflammatory response.\n    *   *Basic Metabolic Panel:* Evaluates kidney function and electrolyte balance, crucial for patients with diabetes, hypertension, and to monitor for dehydration related to fever.\n*   **Advise rest and supportive care:** Supportive care can help manage the symptoms while waiting for definitive diagnosis and treatment. Acetaminophen or ibuprofen can reduce fever and pain. Consider potential drug interactions with diabetes medication (consult physician or pharmacist).\n*   **Proximity of Hospitals:** Providing the nearest hospitals ensures the patient knows where to go for immediate care if their symptoms worsen significantly before their primary care appointment, especially considering the reported dizziness.\n*   **Preference for In-Person Visit:** The patient's age (67), reported dizziness, mobility issues (cane use), and preferred mode of care (in-person) make a physical examination important for a thorough assessment and to avoid potential misinterpretations from a remote consultation. A physical exam can help assess balance, coordination, and neurological function, all of which are relevant given the dizziness.\n*   **Allergies and Chronic Conditions:** The care team should be aware of the allergies to Penicillin and Latex, along with the patient's Chronic Conditions of Type 2 Diabetes and Mild Hypertension when suggesting the appropriate treatment to avoid any adverse reactions.\n"

In [60]:
# Display the output in a clean, formatted manner
print("\n===== Customized Treatment Plan =====\n")

# Split sections if the model followed the prompt structure
sections = response.text.strip().split('\n\n')

for section in sections:
    if section.strip():
        print(section)
        print("-" * 60)  # Divider between sections

===== Customized Treatment Plan =====

Here's a proposed treatment plan based on the provided patient information.
------------------------------------------------------------
**1. Medical Actions**
------------------------------------------------------------
*   **Schedule a Primary Care Visit:** Within 24-48 hours.
*   **Recommend Lab Tests:** CBC (Complete Blood Count), CRP (C-Reactive Protein), and basic metabolic panel.
*   **Advise rest and supportive care:** Get adequate rest, stay hydrated, and consider over-the-counter fever reducers/pain relievers like acetaminophen (Tylenol) or ibuprofen (Advil), being mindful of potential interactions with existing medications.
------------------------------------------------------------
**2. Location-Specific Options**
------------------------------------------------------------
*   **Nearest Hospitals (for potential urgent care if symptoms worsen significantly):**
    *   Christ Hospital (approximately 0.56 miles from patient's coordinates).
    *   Cincinnati VA Medical Center (approximately 0.65 miles from patient's coordinates).
    *   University of Cincinnati Medical Center (approximately 0.71 miles from patient's coordinates).
*   **Consider in-person visit:** Given the patient's reported occasional dizziness, preferred mode of care, and age, an in-person assessment is preferred over a telehealth visit initially.
------------------------------------------------------------
**3. Justifications**
------------------------------------------------------------
*   **Schedule a Primary Care Visit:** The combination of fever, headache, and soreness is indicative of a potential infection (viral or bacterial) or inflammatory process. A primary care physician can assess the patient's overall condition, rule out serious causes, and prescribe appropriate treatment.
*   **Recommend Lab Tests (CBC, CRP, Basic Metabolic Panel):**
    *   *CBC:* Helps to identify signs of infection (elevated white blood cell count) or other blood disorders.
    *   *CRP:* An elevated CRP level indicates inflammation in the body, which can help differentiate between viral and bacterial infections and assess the severity of the inflammatory response.
    *   *Basic Metabolic Panel:* Evaluates kidney function and electrolyte balance, crucial for patients with diabetes, hypertension, and to monitor for dehydration related to fever.
*   **Advise rest and supportive care:** Supportive care can help manage the symptoms while waiting for definitive diagnosis and treatment. Acetaminophen or ibuprofen can reduce fever and pain. Consider potential drug interactions with diabetes medication (consult physician or pharmacist).
*   **Proximity of Hospitals:** Providing the nearest hospitals ensures the patient knows where to go for immediate care if their symptoms worsen significantly before their primary care appointment, especially considering the reported dizziness.
*   **Preference for In-Person Visit:** The patient's age (67), reported dizziness, mobility issues (cane use), and preferred mode of care (in-person) make a physical examination important for a thorough assessment and to avoid potential misinterpretations from a remote consultation. A physical exam can help assess balance, coordination, and neurological function, all of which are relevant given the dizziness.
*   **Allergies and Chronic Conditions:** The care team should be aware of the allergies to Penicillin and Latex, along with the patient's Chronic Conditions of Type 2 Diabetes and Mild Hypertension when suggesting the appropriate treatment to avoid any adverse reactions.
------------------------------------------------------------

In [61]:
#Gemini-output looks good enough to me.
#lets work with Langchain on next notebook to create multi agentic models to see if it performs any better.